import { Contract } from "./../../model/contract";
import { Injectable } from "@angular/core";

@Injectable({
  providedIn: "root",
})
export class ContractService {
  contractList: Contract[] = [
    {
      contractId: 1,
      customer: {
        id: 1,
        customerType: "Platinium",
        customerName: "Lý Huỳnh Hữu Trí",
        customerBirthday: "20/10/2001",
        customGender: true,
        customerIdCard: "0191903819231",
        customerPhone: "0333915138",
        customerEmail: "lytri102@gmail.com",
        customerAddress: "Quảng Nam",
      },
      service: {
        id: 3,
        image: "../assets/service/1.png",
        serviceName: "Phòng Họp",
        serviceArea: 4,
        serviceCost: 1000,
        serviceMaxPeople: 12,
        rentType: "Month>",
        serviceType: "villa",
        standardRoom: "VIP",
        descriptionOtherConvenience: "Bếp Nướng",
        poolArea: 900,
        numberOfFloors: 12,
      },
      startDateContract: "20/10/2021",
      endDateContract: "20/10/2021",
      contractDeposits: 1000,
      contractTotalMoney: 1000,
    },
    {
      contractId: 1,
      customer: {
        id: 1,
        customerType: "Platinium",
        customerName: "Lý Huỳnh Hữu Trí",
        customerBirthday: "20/10/2001",
        customGender: true,
        customerIdCard: "0191903819231",
        customerPhone: "0333915138",
        customerEmail: "lytri102@gmail.com",
        customerAddress: "Quảng Nam",
      },
      service: {
        id: 3,
        image: "../assets/service/1.png",
        serviceName: "Phòng Họp",
        serviceArea: 4,
        serviceCost: 1000,
        serviceMaxPeople: 12,
        rentType: "Month>",
        serviceType: "villa",
        standardRoom: "VIP",
        descriptionOtherConvenience: "Bếp Nướng",
        poolArea: 900,
        numberOfFloors: 12,
      },
      startDateContract: "20/10/2021",
      endDateContract: "20/10/2021",
      contractDeposits: 1000,
      contractTotalMoney: 1000,
    },
    {
      contractId: 1,
      customer: {
        id: 1,
        customerType: "Platinium",
        customerName: "Lý Huỳnh Hữu Trí",
        customerBirthday: "20/10/2001",
        customGender: true,
        customerIdCard: "0191903819231",
        customerPhone: "0333915138",
        customerEmail: "lytri102@gmail.com",
        customerAddress: "Quảng Nam",
      },
      service: {
        id: 3,
        image: "../assets/service/1.png",
        serviceName: "Phòng Họp",
        serviceArea: 4,
        serviceCost: 1000,
        serviceMaxPeople: 12,
        rentType: "Month>",
        serviceType: "villa",
        standardRoom: "VIP",
        descriptionOtherConvenience: "Bếp Nướng",
        poolArea: 900,
        numberOfFloors: 12,
      },
      startDateContract: "20/10/2021",
      endDateContract: "20/10/2021",
      contractDeposits: 1000,
      contractTotalMoney: 1000,
    },
    {
      contractId: 1,
      customer: {
        id: 1,
        customerType: "Platinium",
        customerName: "Lý Huỳnh Hữu Trí",
        customerBirthday: "20/10/2001",
        customGender: true,
        customerIdCard: "0191903819231",
        customerPhone: "0333915138",
        customerEmail: "lytri102@gmail.com",
        customerAddress: "Quảng Nam",
      },
      service: {
        id: 3,
        image: "../assets/service/1.png",
        serviceName: "Phòng Họp",
        serviceArea: 4,
        serviceCost: 1000,
        serviceMaxPeople: 12,
        rentType: "Month>",
        serviceType: "villa",
        standardRoom: "VIP",
        descriptionOtherConvenience: "Bếp Nướng",
        poolArea: 900,
        numberOfFloors: 12,
      },
      startDateContract: "20/10/2021",
      endDateContract: "20/10/2021",
      contractDeposits: 1000,
      contractTotalMoney: 1000,
    },
    {
      contractId: 1,
      customer: {
        id: 1,
        customerType: "Platinium",
        customerName: "Lý Huỳnh Hữu Trí",
        customerBirthday: "20/10/2001",
        customGender: true,
        customerIdCard: "0191903819231",
        customerPhone: "0333915138",
        customerEmail: "lytri102@gmail.com",
        customerAddress: "Quảng Nam",
      },
      service: {
        id: 3,
        image: "../assets/service/1.png",
        serviceName: "Phòng Họp",
        serviceArea: 4,
        serviceCost: 1000,
        serviceMaxPeople: 12,
        rentType: "Month>",
        serviceType: "villa",
        standardRoom: "VIP",
        descriptionOtherConvenience: "Bếp Nướng",
        poolArea: 900,
        numberOfFloors: 12,
      },
      startDateContract: "20/10/2021",
      endDateContract: "20/10/2021",
      contractDeposits: 1000,
      contractTotalMoney: 1000,
    },
  ];

  constructor() {}

  getAll() {
    return this.contractList;
  }
}
